### ISSUE TITLE
[BUG]Need what special dependence or specific version, always error, can not start normally

### ISSUE THREAD

**Issue by alenhrp** [alpertunga-bile/prompt-generator-comfyui#14]
![image](https://github.com/alpertunga-bile/prompt-generator-comfyui/assets/99852817/823447a5-c8f7-4b4d-b27a-2c8ce7989ec6)
Need what special dependence or specific version, always error, can not start normally？

**Comment by alpertunga-bile** [comment]
Hello, thanks for reporting. I did a clean setup and it seems the node is working. Here are the steps that I did:

1. Download and extract the latest portable version of the ComfyUI which is ```ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z```.
2. Go to the ```ComfyUI_windows_portable``` folder and run the ```run_nvidia_gpu.bat``` file to check if everything is working.
3. Add a Stable Diffusion model under the ```models/checkpoints``` folder.
4. Download the ```female_positive_generator_v2``` prompt generator model from [this link](https://drive.google.com/drive/folders/1c21kMH6FTaia5C8239okL3Q0wJnnWc1N?usp=share_link) to the ```models/prompt_generators``` folder and extract it there.
5. Go to the ```custom_nodes``` folder and clone the repository with the ```git clone https://github.com/alpertunga-bile/prompt-generator-comfyui.git``` command.
6. Go to the ```ComfyUI_windows_portable``` folder again and run the ```run_nvidia_gpu.bat``` file to check if everything is working.

The code is checking if the ```python_embeded``` folder is present or not so executing the ```run_nvidia_gpu.bat``` file in the ```ComfyUI_windows_portable``` folder is essential.

I hope these steps are solved your issue if it is not please let me know.

**Comment by alenhrp** [comment]
> Hello, thanks for reporting. I did a clean setup and it seems the node is working. Here are the steps that I did:
> 
> 1. Download and extract the latest portable version of the ComfyUI which is `ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z`.
> 2. Go to the `ComfyUI_windows_portable` folder and run the `run_nvidia_gpu.bat` file to check if everything is working.
> 3. Add a Stable Diffusion model under the `models/checkpoints` folder.
> 4. Download the `female_positive_generator_v2` prompt generator model from [this link](https://drive.google.com/drive/folders/1c21kMH6FTaia5C8239okL3Q0wJnnWc1N?usp=share_link) to the `models/prompt_generators` folder and extract it there.
> 5. Go to the `custom_nodes` folder and clone the repository with the `git clone https://github.com/alpertunga-bile/prompt-generator-comfyui.git` command.
> 6. Go to the `ComfyUI_windows_portable` folder again and run the `run_nvidia_gpu.bat` file to check if everything is working.
> 
> The code is checking if the `python_embeded` folder is present or not so executing the `run_nvidia_gpu.bat` file in the `ComfyUI_windows_portable` folder is essential.
> 
> I hope these steps are solved your issue if it is not please let me know.

Yes, I did what you said, but the problem remained.
![image](https://github.com/alpertunga-bile/prompt-generator-comfyui/assets/99852817/6d747eeb-169b-49fc-92e2-2c1f5cd2ebe7)


![image](https://github.com/alpertunga-bile/prompt-generator-comfyui/assets/99852817/7029415a-458b-466b-95e1-1991774cd998)

**Comment by alenhrp** [comment]
> > Hello, thanks for reporting. I did a clean setup and it seems the node is working. Here are the steps that I did:
> > 
> > 1. Download and extract the latest portable version of the ComfyUI which is `ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z`.
> > 2. Go to the `ComfyUI_windows_portable` folder and run the `run_nvidia_gpu.bat` file to check if everything is working.
> > 3. Add a Stable Diffusion model under the `models/checkpoints` folder.
> > 4. Download the `female_positive_generator_v2` prompt generator model from [this link](https://drive.google.com/drive/folders/1c21kMH6FTaia5C8239okL3Q0wJnnWc1N?usp=share_link) to the `models/prompt_generators` folder and extract it there.
> > 5. Go to the `custom_nodes` folder and clone the repository with the `git clone https://github.com/alpertunga-bile/prompt-generator-comfyui.git` command.
> > 6. Go to the `ComfyUI_windows_portable` folder again and run the `run_nvidia_gpu.bat` file to check if everything is working.
> > 
> > The code is checking if the `python_embeded` folder is present or not so executing the `run_nvidia_gpu.bat` file in the `ComfyUI_windows_portable` folder is essential.
> > I hope these steps are solved your issue if it is not please let me know.
> 
> Yes, I did what you said, but the problem remained. ![image](https://private-user-images.githubusercontent.com/99852817/328020659-6d747eeb-169b-49fc-92e2-2c1f5cd2ebe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjI0MDcsIm5iZiI6MTcxNTIyMjEwNywicGF0aCI6Ii85OTg1MjgxNy8zMjgwMjA2NTktNmQ3NDdlZWItMTY5Yi00OWZjLTkyZTItMmMxZjVjZDJlYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NGQ5NGMwZjEzOWE2ODEyOTZmMGU2MWM2ODlhYTQ4NWY5YmQ5ZmM3NzRmZjllYTNmNTM0YWE3YWZmYmU3YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9aeXuj_wZ3HJ2UAPP--xmRmqvEnZW4rpOgYkhQheIfY)
> 
> ![image](https://private-user-images.githubusercontent.com/99852817/328020640-7029415a-458b-466b-95e1-1991774cd998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjI0MDcsIm5iZiI6MTcxNTIyMjEwNywicGF0aCI6Ii85OTg1MjgxNy8zMjgwMjA2NDAtNzAyOTQxNWEtNDU4Yi00NjZiLTk1ZTEtMTk5MTc3NGNkOTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyMzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOWY4ZWJiYThjOWNlYmI5N2RlNjdkMTFjOWJmZjZlNzA3MTNlODA1NzI0NzI2OGQxYWU0OTJhM2E5NDFmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EV--x48-iwroTqyLk6q_nxLHluYSthTFVrHrKX_2G3k)

I have now switched to **female_positive_generator_v2 again**, but still **IMPORT FAILED** on startup, please check and verify, thanks!

**Comment by alpertunga-bile** [comment]
Hello, @alenhrp. After searching, I found the answer. I am assuming that you are using this [ZHO-ComfyUI](https://github.com/ZHO-ZHO-ZHO/ComfyUI-ZHO-Chinese) repository and you are facing this error:

![error](https://github.com/alpertunga-bile/prompt-generator-comfyui/assets/76731692/69a970f3-38fb-4523-9337-66a10489daf9)

You are facing this error not because of the node but because of the [ZHO-ComfyUI](https://github.com/ZHO-ZHO-ZHO/ComfyUI-ZHO-Chinese) repository. The repository is not up-to-date with the [ComfyUI](https://github.com/comfyanonymous/ComfyUI) repository so it misses some parts of the updates and it causes the error.

So how can you overcome this issue? You can download the [ComfyUI](https://github.com/comfyanonymous/ComfyUI) repository and copy the:
- app
- comfy
- comfy_extras
- input
- user 
folders and
- cuda_malloc.py
- execution.py
- folder_paths.py
- latent_preview.py
- main.py
- new_updater.py
- node_helpers.py
- nodes.py
- server.py 
files to your ComfyUI folder. 

Or you can use the [ComfyUI](https://github.com/comfyanonymous/ComfyUI) repository and download and replace with the folders from the [ZHO-ComfyUI](https://github.com/ZHO-ZHO-ZHO/ComfyUI-ZHO-Chinese?tab=readme-ov-file#%E4%B8%8B%E8%BD%BD)'s download section.

I tried with the first option and it seems working.

**Comment by alenhrp** [comment]
Thank you very much for your detailed identification and analysis!
Although my directory name is "Zho_Chinese_ComfyUl_windows_portable", my local code is already in the (https://github.com/comfyanonymous/ComfyUI) library and updated daily with the latest changes.
